# Generated by Django 3.2.6 on 2021-08-31 00:54

from django.db import migrations, models
import django.db.models.deletion
import django_measurement.models
import measurement.measures.volume


class Migration(migrations.Migration):

    dependencies = [
        ('drinks_menu', '0001_initial'),
    ]

    state_operations = [
            migrations.CreateModel(
                name='MeasuredIngredient',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('volume', django_measurement.models.MeasurementField(measurement=measurement.measures.volume.Volume)),
                    ('drink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drinks_menu.drink')),
                    ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drinks_menu.ingredient')),
                ],
            ),
            migrations.AlterModelTable(
                name='measuredingredient',
                table='drinks_menu_drink_ingredients',
            ),
            migrations.AlterField(
                model_name='drink',
                name='ingredients',
                field=models.ManyToManyField(through='drinks_menu.MeasuredIngredient', to='drinks_menu.Ingredient'),
            ),
        ]


    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
            migrations.AddField(
                model_name='MeasuredIngredient',
                name='volume',
                field=django_measurement.models.MeasurementField(measurement=measurement.measures.volume.Volume, default=measurement.measures.volume.Volume(us_oz=0)),
                preserve_default=False
            ),
            migrations.AlterModelTable(
                name='measuredingredient',
                table=None,
            ),
        ]

