# Generated by Django 3.2.6 on 2021-08-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks_menu', '0002_auto_20210831_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
