# Generated by Django 3.2.6 on 2021-09-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks_menu', '0003_drink_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_liquor',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drink',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='drink_images/'),
        ),
    ]
