# Generated by Django 3.2.6 on 2021-09-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks_menu', '0004_auto_20210903_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='directions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
