# Generated by Django 3.2.6 on 2021-09-07 04:30

from django.db import migrations, models
import django.db.models.deletion
from drinks_menu.models import Glassware

# Called by RunPython to create a default glassware for the drink foreign key
def add_tumbler(apps, schema_editor):
    tumbler = Glassware(name="Tumbler")
    tumbler.save()

# Makes this migration reversible
def remove_tumbler(apps, schema_editor):
    # We don't need to do anything here because
    # the model get's deleted in this migration so
    # removing the Tumbler object would be redundant
    # and it causes issues because django thinks it
    # needs to delete the key out of the drinks that
    # (used to) reference Tumbler so it errors.
    #
    # Tested it and it seems to work :shrug:
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('drinks_menu', '0005_drink_directions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glassware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RunPython(add_tumbler, remove_tumbler),
        migrations.AddField(
            model_name='drink',
            name='glass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='drinks_menu.glassware'),
            preserve_default=False,
        ),
    ]
